FROM node:latest

WORKDIR /app

ENV --from-env=.env
# Copy package.json + package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Start the dev server


CMD ["npm", "run", "build","npm","run", "start"]